### ISSUE TITLE
Support iosSimulatorArm64 architecture

### ISSUE THREAD

**Issue by kirillzh** [ACINQ/bitcoin-kmp#77]
Getting this error when targeting `iosSimulatorArm64`

```
  > No matching variant of fr.acinq.bitcoin:bitcoin-kmp:0.10.0 was found. The consumer was configured to find a usage of 'kotlin-api' of a library, preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64' but:
      - Variant 'iosArm64ApiElements-published' capability fr.acinq.bitcoin:bitcoin-kmp:0.10.0 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
          - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'
          - Other compatible attribute:
              - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
```

**Comment by sstone** [comment]
What do you mean by "targeting iosSimulatorArm64" ? How do you trigger this error ? for example are you trying to run tests against an arm64 emulator on a M1 (or M2) machine ?

**Comment by kirillzh** [comment]
@sstone, that's right, on M1 we need to run an ARM64 simulator, which requires configuring `iosSimulatorArm64()` target. It is not configured as part of `ios()` by default ([KT-50615](https://youtrack.jetbrains.com/issue/KT-50615)), so it needs to be setup manually, for example [like so](https://github.com/cashapp/turbine/blob/trunk/build.gradle#L24-L27).

**Comment by sstone** [comment]
The issue is that we don't provide secp256k1 bindings for macos M1, which is probably what is needed here.
It's a very low priority for us: we don't need it (we can build our iOS app just fine), we would not use it and there is no support yet on github CI (see https://github.com/actions/runner-images/issues/2187#issuecomment-1297663254) or any other CI afaik so we would need to build it manually or host an M1 runner ourselves and we don't want to do that. Of course if github does eventually support macos M1 we will add the missing bindings but I would not hold my breath (the issue above was opened nearly 2 years ago...).
